### ISSUE TITLE
Platform mode doesn't work in space?

### ISSUE THREAD

**Issue by tobitege** [TheGreatSardini/Default--#1]
Hello Sardini,
with latest version, I've set both Flight and Parking modes to Platform.
I'm landed on my space station and can lift off with G and then SPACE.
But then I only can yaw my ship but neither W/S nor mouse wheel make any changes.
I can only press G again and it safely lands the ship.
If the platform mode is not aimed to work in space, it shouldn't be possible to activate it?

**Comment by TheGreatSardini** [comment]
I believe I fixed this in the new version I'm working on. 
Quite a few small bugs I've noticed with how the script interacts with space station landing that I'm tweaking.
